services:
  warp:
    build: .
    image: warp_daisuki:latest
    container_name: warp_test
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - "1080:1080/tcp"
      - "8080:8080/udp"
    environment:
      - LANG=C.UTF-8
    volumes:
      - warp_data:/var/lib/cloudflare-warp
    networks:
      - warp_net
    restart: unless-stopped

volumes:
  warp_data:

networks:
  warp_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
        - subnet: "fd00:dead:beef::/48"
